name: s3-deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    env:
       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - name: copy to s3 
      run: |
       aws s3 sync . "$AWS_S3_BUCKET"
       echo "file Updated"
       echo "Website updated"
    - name: deploy to s3 bucket
      run: aws s3 cp index.html s3://"${{secrets.AWS_S3_BUCKET}}"
        
