name: s3-deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - name: copy to s3 
      run: |
       aws s3 sync . "$AWS_S3_BUCKET"
       echo "file Updated"
       echo "Website updated"
  #  - name: Invalidation request   
   #   run: |
         

      env:
       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
       #CLOUDFRONT_ID: ${{secrets.CLOUDFRONT_ID}}
        
