name: s3-deploy

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: self-hosted
    #- uses: jakejarvis/s3-sync-action@master
      #with:
        #args: --acl public-read --follow-symlinks --delete 
    env:
       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} 
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }} 
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }} 
        #AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1fffff
      
    steps:
    - uses: actions/checkout@v3
    - name: uploading to s3
      run: |
       echo "running"
     #  aws s3 sync . "${{ secrets.AWS_S3_BUCKET }}"
        
